# Change these first
owner: conuti-das # Your GitHub organization or username, where this repository lives
repo: status-nbsap # The name of this repository

sites:
  - name: CC - API GATEWAY
    url: $GATEWAY_URL
  - name: CC - API PORTAL
    url: $PORTAL_URL
  - name: CC - API MANAGEMENT
    url: $APIMANAGEMENT_URL
  - name: CC - BACKOFFICE API
    url: $BACKOFFICE_API
  - name: CC - BACKOFFICE WEB
    url: $BACKOFFICE_WEB
  - name: CC - KEYCLOAK
    url: $KEYCLOAK_URL
  - name: CC - PMON API
    url: $PMON_URL
  - name: CC - BACKOFFICE POC
    url: https://dev.netz-sap.macoapp.de
  - name: CC - RABBITMQ MANAMGEMENT
    url: $RABBITMQ_MANAGEMENT
  - name: MCS - ADMIN UI
    url: $MCS_ADMIN
  - name: MCS - PORTAL UI
    url: $MCS_PORTAL
  - name: MCS - BUILD INFO UI
    url: $MCS_BUILD_INFO
  - name: MCS - UI
    url: $MCS_UI
  - name: MPS - CAMUNDA
    url: $MPS_CAMUNDA
  - name: MPS - DATAKEEPER
    url: $DATAKEEPER_URL
  - name: MPS - DATAKEEPER API SEARCH
    url: $DATAKEEPER_SEARCH_URL
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: MPS - DK PROCESS HISTORY
    url: $DATAKEEPER_PH_URL
  - name: MPS - ERP KONNEKTOR TEST
    url: $KONNEKTOR_URL
  - name: MPS - NIFI
    url: $MPS_NIFI
  - name: MPS - TASKER
    url: $TASKER_URL
  - name: MPS - TESTPROCESS
    url: $TESTPROCESS_URL
    __dangerous__body_down_if_text_missing: '"status":"up"'
  - name: MPS - TEMPLATER
    url: $TEMPLATER_URL



status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status-nbsap
  logoUrl: https://conuti.de/wp-content/uploads/2023/05/CONUTI-MACO-APP-Icon_blau_gruen-300x284.png
  name: NETZ SAP Stage
  introTitle: "**NETZ** Status"
  introMessage: Components status overview page
  navbar:
    - title: Status
      href: /status-nbsap
    - title: Backoffice
      href: https://dev.netz-sap.macoapp.de

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
